let isTracking=!1;let totalDistance=0;let lastPosition=null;let startTime=null;let watchId=null;let timerInterval=null;const distanceElement=document.getElementById('distance');const durationElement=document.getElementById('duration');const avgSpeedElement=document.getElementById('avgSpeed');const trackingStatus=document.getElementById('trackingStatus');const startBtn=document.getElementById('startBtn');const stopBtn=document.getElementById('stopBtn');const statusMessage=document.getElementById('statusMessage');function calculateDistance(lat1,lon1,lat2,lon2){const R=6371;const dLat=(lat2-lat1)*Math.PI/180;const dLon=(lon2-lon1)*Math.PI/180;const a=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)*Math.sin(dLon/2);const c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));return R*c}
function formatTime(seconds){const hours=Math.floor(seconds/3600);const minutes=Math.floor((seconds%3600)/60);const secs=seconds%60;return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`}
function updateTimer(){if(startTime){const elapsed=Math.floor((Date.now()-startTime)/1000);durationElement.textContent=formatTime(elapsed);if(elapsed>0){const avgSpeed=(totalDistance/elapsed)*3600;avgSpeedElement.textContent=avgSpeed.toFixed(1)+' km/h'}}}
function handlePosition(position){const{latitude,longitude}=position.coords;if(lastPosition){const distance=calculateDistance(lastPosition.latitude,lastPosition.longitude,latitude,longitude);if(distance>0.005){totalDistance+=distance;distanceElement.textContent=totalDistance.toFixed(2)}}
lastPosition={latitude,longitude}}
function handleError(error){statusMessage.textContent='✗ Unable to get location: '+error.message;statusMessage.style.backgroundColor='#ffebee';statusMessage.style.borderLeftColor='#f44336';stopTracking()}
function startTracking(){if(!navigator.geolocation){statusMessage.textContent='✗ Geolocation not supported';statusMessage.style.backgroundColor='#ffebee';statusMessage.style.borderLeftColor='#f44336';return}
isTracking=!0;totalDistance=0;lastPosition=null;startTime=Date.now();startBtn.style.display='none';stopBtn.style.display='block';trackingStatus.textContent='Tracking...';trackingStatus.style.color='#4caf50';statusMessage.textContent='✓ GPS tracking active';statusMessage.style.backgroundColor='#e8f5e9';statusMessage.style.borderLeftColor='#4caf50';watchId=navigator.geolocation.watchPosition(handlePosition,handleError,{enableHighAccuracy:!0,maximumAge:0,timeout:5000});timerInterval=setInterval(updateTimer,1000)}
function stopTracking(){isTracking=!1;if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}
if(timerInterval){clearInterval(timerInterval);timerInterval=null}
startBtn.style.display='block';stopBtn.style.display='none';trackingStatus.textContent='Stopped';trackingStatus.style.color='#f44336';statusMessage.textContent='✓ Walk completed!';statusMessage.style.backgroundColor='#e3f2fd';statusMessage.style.borderLeftColor='#2196f3'}
startBtn.addEventListener('click',startTracking);stopBtn.addEventListener('click',stopTracking)