const prefersReducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const themeToggle=document.getElementById('themeToggle');const themeStatus=document.getElementById('themeStatus');const notificationToggle=document.getElementById('notificationToggle');const notificationStatus=document.getElementById('notificationStatus');const soundToggle=document.getElementById('soundToggle');const soundStatus=document.getElementById('soundStatus');

// Adds a brief state pulse to custom switches so the update is easy to notice.
function flashToggle(toggleElement,statusElement){if(prefersReducedMotion){return}
if(toggleElement){toggleElement.classList.add('is-updating');window.setTimeout(()=>{toggleElement.classList.remove('is-updating')},260)}
if(statusElement){statusElement.classList.remove('is-updated');void statusElement.offsetWidth;statusElement.classList.add('is-updated');window.setTimeout(()=>{statusElement.classList.remove('is-updated')},260)}}
function initializeSettings(){loadTheme();loadNotificationSetting();loadSoundSetting()}
function loadTheme(){const savedTheme=localStorage.getItem('fitTrackTheme');if(savedTheme==='dark'){document.body.classList.add('dark');themeToggle.classList.add('active');themeStatus.textContent='Theme: Dark Mode'}else{document.body.classList.remove('dark');themeToggle.classList.remove('active');themeStatus.textContent='Theme: Light Mode'}}
function toggleThemeUI(){const isDark=toggleThemeGlobal();if(isDark){themeToggle.classList.add('active');themeStatus.textContent='Theme: Dark Mode'}else{themeToggle.classList.remove('active');themeStatus.textContent='Theme: Light Mode'}flashToggle(themeToggle,themeStatus)}
window.handleThemeToggle=toggleThemeUI;function loadNotificationSetting(){const notificationEnabled=localStorage.getItem('fitTrackNotifications');if(notificationEnabled===null||notificationEnabled==='on'){notificationToggle.classList.add('active');notificationStatus.textContent='Notifications: On';localStorage.setItem('fitTrackNotifications','on')}else{notificationToggle.classList.remove('active');notificationStatus.textContent='Notifications: Off'}}
function toggleNotification(){notificationToggle.classList.toggle('active');const isOn=notificationToggle.classList.contains('active');localStorage.setItem('fitTrackNotifications',isOn?'on':'off');notificationStatus.textContent=isOn?'Notifications: On':'Notifications: Off';flashToggle(notificationToggle,notificationStatus)}
function loadSoundSetting(){const soundEnabled=localStorage.getItem('fitTrackSound');if(soundEnabled===null||soundEnabled==='on'){soundToggle.classList.add('active');soundStatus.textContent='Sound Effects: On';localStorage.setItem('fitTrackSound','on')}else{soundToggle.classList.remove('active');soundStatus.textContent='Sound Effects: Off'}}
function toggleSound(){soundToggle.classList.toggle('active');const isOn=soundToggle.classList.contains('active');localStorage.setItem('fitTrackSound',isOn?'on':'off');soundStatus.textContent=isOn?'Sound Effects: On':'Sound Effects: Off';flashToggle(soundToggle,soundStatus)}
notificationToggle.addEventListener('click',toggleNotification);soundToggle.addEventListener('click',toggleSound);initializeSettings()